tmr.alarm(1, 30000, 1, function()
    print("-----------------------------------")
    print("Read the sensors")
    dofile("dht22.lua")
    collectgarbage()
    dofile("bmp085.lua")
    collectgarbage()
    dofile("string_p.lua")
    print(string.format("t = %s;h = %s;p = %s",t,h,p))
    collectgarbage()
    dofile("thingspeak.lua")
    collectgarbage()
    end
    )
